### ISSUE TITLE
currentEntityKeys v CurrentEntityKey

### ISSUE THREAD

**Issue by richardshergold** [briebug/ngrx-auto-entity#63]
I think there may be an issue with the single/multiple selection of Entities.

If I select item(s) using selectMany such that I then have a value in currentEntityesKeys I can then do

`this.currentSet$.pipe(take(1)).subscribe`

If an item is selected singularly using myFacade.current$ i.e so that currentEntityKey is populated then the above line results in the error:

```
breadcrumbs.js:58 ERROR TypeError: Cannot read property 'map' of undefined
    at briebug-ngrx-auto-entity.js:1570
    at store.js:576
    at memoized (store.js:518)
    at defaultStateFn (store.js:545)
    at store.js:579
    at memoized (store.js:518)
    at MapSubscriber.project (store.js:473)
```

**Comment by jrista** [comment]
Currently, multi-selections and single selections are supposed to be distinct. You should be able to select a single entity and that should work regardless of whether you have a multi-selection or not, and regardless of whether the single entity is also in the current multi-selection. 

Given that, I may need some more information here. If you dispatch a `Select` action, then try to use `currentSet$`, there would not be any entities in the current set to retrieve. NOW, the library most certainly should not throw an error if you try to access the current set when there are no selected entities, and I should be able to fix that relatively easily.

I want to make sure however that you are using selections properly. Dispatching `Select` will not add that single entity to the current set. By design, `Select` and the "current entity" is distinct from `SelectMany` and the "current set". The two are not cross-linked or otherwise related. 

If you need to use `currentSet$`, then make sure you are using `SelectMany` as you can always select an array of just one item. You can then `SelectMore` to add to that set, or `DeselectMany/All` to remove from that set. 

Use `Select` to use `current$` and track a single entity selection. I felt it was useful to support both single entity and sets of entities in selection concurrently. You might, for example, need to scan through the entities of a set selection, and maybe display a popup or something like that for one of the entities of that selection. By having `Select` be distinct from `SelectMany`, this is possible.

**Comment by richardshergold** [comment]
Thanks @jrista I will check my code and make sure I am selecting items correctly.

**Comment by richardshergold** [comment]
@jrista that's working better now - I hadn't got my head round the two selections methods being totally distinct - I have various ways in which items can be selected, I just have to be careful :-)

**Comment by jrista** [comment]
Ok, glad you got it figured! I'll add some better documentation around selections once I get the chance, as yes, the fact that they are distinct selections is not necessarily obvious or intuitive.
