### ISSUE TITLE
Feature Request- allow ofEntityType to accept multiple types.

### ISSUE THREAD

**Issue by mxdmedia** [briebug/ngrx-auto-entity#66]
On convenient feature of ngrx's entities, is the ability to specify multiple actions in `ofType` to trigger an effect.  It would be great to do the same using auto-entity's `ofEntityType` function.  A tricky part of this would be the function interface, as two parameters are required for each defined `entityType`.  A couple of possibilities:

Allow multiples of two parameters up to say, 5 total actions.  E.g.:
```typescript
ofEntityType(Model1, EntityActionTypes.LoadAll, Model2, EntityActionTypes.LoadAll, ...)
```
I'm not a huge fan of this, as it seems a bit.. unwieldy and hard to read.

Another option- group each in an object:
```typescript
ofEntityType(
  {entity: Model1, action: EntityActionTypes.LoadAll},
  {entity: Model2, action: EntityActionTypes.LoadAll},
  ...
)
```
I like this better, but it is definitely a bit more verbose.  And to standardize the interface, you'd need to require it for even a single entry.

**Comment by jrista** [comment]
I will see what i can do here. These are generic operators, and when you involve multiple types sometimes the typing through the rest of the pipe can get quirky. Now when we originally wrote the library, we were trying to support Angular and NGRX back to v6. We now only support 8+, which also means we will require newer version of TypeScript, which might make a richer ofEntityType operator possible.

**Comment by mxdmedia** [comment]
One thought- is there a function (or could one be created) that returns the proper enum/string that ngrx's `ofType` requires?  e.g.:
```typescript
ofType(
  aeActionType(Model1, EntityActionTypes.LoadAll), // returns '[Model1] (generic) LoadAll'
  aeActionType(Model2, EntityActionTypes.LoadAll)  // returns '[Model2] (generic) LoadAll'
)
```
That way a user could just use ngrx's `ofType` if they want to trigger an effect with multiple actions.

**Comment by jrista** [comment]
If you use ofType that way, you would not actually be filtering on the model type as well. You can already use just ofType with EntityActionTypes. But, such effects will operate on all entities regardless of which ones. 

The ofEntityType operator is designed to allow you to filter on both action type and model simultaneously. The trick here is getting the types to thread through the observable pipe properly... I may be limited by what TypeScript supports. TS 3.x has much richer types than 2.x though, and I may be able to find a way to support multiple entity model types if I can figure out the right typing.

**Comment by mxdmedia** [comment]
I think we're talking about the same thing, or I've totally misunderstood how `ofType` and `ofEntityType` works.  I think a concrete scenario might illustrate what I'm trying to accomplish (and I am all ears for other ways to get this done).

I have a model, with an array of tags attached to it.  The models look something like:
```typescript
class Snippet {
  @Key id: string;
  title: sting;
  body: string;
  tags: string[];  // Correspond to SnippetTag.tag
}

class SnippetTag {
  @Key tag: string;     // a unique slug that is human readable, e.g.: 'neat-tag'
  description: string;
  count: number;       // Number of Snippets this tag is attached to
}
```
My api has an endpoint that returns the top 10 tags, along with their count, to be displayed in a side-bar.  Thus, any time I create, update, or delete a Snippet, I need to re-grab my top-10 tags as they may have changed.  One way of doing this, was using the `savedAt`, `deletedAt`, and `createdAt` selectors to trigger my actions (hence my opening of the missing `createdAt` selector issue).   I also thought of implementing this as an effect.  I was trying to avoid making three separate effects to do so.  Something like:
```typescript
  chageSnippetExtrasEffect$ = createEffect(
    () =>
      this.actions$.pipe(
        ofType(
          '[Snippet] CreateSuccess',
          '[Snippet] UpdateSuccess',
          '[Snippet] DeleteSuccess'
        ),
        tap(() => {
          this.store.dispatch(new LoadTopTen(SnippetTag));
        })
      ),
    { dispatch: false }
  );
```
(I realize I can calculate and update my tag counts on the client side, etc..  This is all in a demo project i use to test new ideas/concepts/libraries/etc..  and I've been putting `auto-entity` through its paces with it.  In one of my other projects, I do have data that must be retrieved from the server after certain entity updates/creation- this is just a much simplified case)

**Comment by jrista** [comment]
So in the example you have shared, you don't seem to care about the type of the model. So ofType will work fine there. However in the case where the type of the model DOES matter to later operators in the pipe, the ofType solution here wouldn't work as well unless you explicitly specified the types:

```typescript
this.actions$.pipe(
    ofType<CreateSuccess<SnippetExtras> | UpdateSuccess<SnippetExtras> | DeleteSuccess<SnippetExtras>(
          '[Snippet] CreateSuccess',
          '[Snippet] UpdateSuccess',
          '[Snippet] DeleteSuccess'
    ),
    // ... do stuff with these possible actions
);
```

This alone is kind of ugly and convoluted, having to specify all those complex types like that. This is one of the benefits that ofEntityType provides, because you are specifying the model type. Only it is currently just one type of model, not many. I may be able to extend it to support many types of models, and encapsulate all the typing complexity within the Auto-Entity library. This would allow you to keep the full benefit of strong, rich types, without having to suffer the consequences of defining them explicitly everywhere.

**Comment by jrista** [comment]
> I was trying to avoid making three separate effects to do so

So, to directly address this concern. First, your particular example is already possible with a single effect, and a single instance of ofEntityType. Since you are not actually working with different entities, you are just working with different actions of the same entity:

```typescript
  chageSnippetExtrasEffect$ = createEffect(
    () =>
      this.actions$.pipe(
        ofEntityType(
          Snippet,
          EntityActionTypes.CreateSuccess, 
          EntityActionTypes.UpdateSuccess,
          EntityActionTypes.DeleteSuccess
        ),
        map(() => new LoadTopTen(SnippetTag))
      )
  );
```

However, assuming you DID need to handle different model types. This should actually be possible now, and maybe this is the proper solution for this. You can always **merge** multiple streams into a single stream:

```typescript
  const CUDActions = [EntityActionTypes.CreateSuccess, EntityActionTypes.UpdateSuccess, EntityActionTypes.DeleteSuccess];
  complexEffect$ = createEffect(
    () =>
      merge(
        this.actions$.pipe(ofEntityType(EntityA, CUDActions)),
        this.actions$.pipe(ofEntityType(EntityB, CUDActions)),
        this.actions$.pipe(ofEntityType(EntityD, CUDActions)),
     ).pipe(
        map(() => new SomeOtherAction(EntityD))
      )
  );
```

Now you are handling multiple actions for multiple entities in a single effect. The beauty of this is, it is composable. It leverages existing RxJs functionality as well as an elementary ofEntityType operator to support more advanced scenarios. TS 3.x should also automatically handle the types here, so you should be able to access unique properties from each entity type without issue.

What I may do is create a wrapper factory function for RxJs that will basically do this for you, just to simplify it a little. Something like:

```typescript
  const CUDActions = [EntityActionTypes.CreateSuccess, EntityActionTypes.UpdateSuccess, EntityActionTypes.DeleteSuccess];
  complexEffect$ = createEffect(
    () =>
      ofEntityTypes(this.actions$, [EntityA, EntityB, EntityC], CUDActions).pipe(
        map(() => new SomeOtherAction(EntityD))
      )
  );
```

**Comment by jrista** [comment]
So, a lot of this is just how extensive your knowledge of RxJs is, I think. ;) RxJs is extremely powerful, but its power is often obscured behind the screen of a major paradigm shift in how you think about programming. 

This is partly the beauty of RxJs and NgRx in general. They are built on top of very declarative, functional paradigms that are highly composable. Sometimes it just requires knowing how to compose all the power of RxJs to achieve what you need in the simplest way possible. 

These tenets of RxJs and NgRx extend to Auto-Entity as well. We love composability, and functional paradigms. So generally, if there is such a solution, we'll probably try to go with that first, before adding something new to the library.

**Comment by jrista** [comment]
@mxdmedia For now, can you give the `merge()` approach a try? I've fiddled with trying to properly type this in the library, and I think it will indeed be complex and arcane enough that I'll need some time to figure out if it is possible at all, and if it is possible...I still need to decide if it is best to try and add more to the library, or just recommend that users of the library resort to using existing rxjs factory functions to solve problems like this. 

I think the merge approach is actually fairly simple, but also pretty clear as to what is going on. I think it is actually clearer than my `ofEntityTypes` concept, which is a little more obscure as to what, exactly, it is intended to do. Consumers of the Auto-Entity library in the long run are bound to learn and remember what it might do, yet I feel the merge approach, even though it may be a little more verbose, is better in the long run due to its clarity. 

Anyway, if you give it a try and it works, great. If you run into any trouble, let me know, and then maybe built-in solution would then be warranted.

**Comment by mxdmedia** [comment]
Wow!  lots of great insight here.

Re: Knowledge of RxJs- this is definitely something I am trying to learn more, as you are right: it is a significant paradigm shift, and you have to look at programming through a very different lens.  I am to the point where I am pretty comfortable writing my own implementations using a handful of the rxjs operators, but when it comes to reading other's implementations, I struggle a bit.  I am definitely a fan of the functional nature of RxJs.. just need to practice more.

I am going to spend some time digesting what you've posted here.  I'm sure I will learn a lot from it!  I will definitely give the merge approach a try, and let you know how it goes.  Thanks again for spending the time on this, and being so candid in your responses.

**Comment by jrista** [comment]
Absolutely! I'm a huge fan of RxJs, and any opportunity to teach people how to do it better, I try, I guess. ;)

**Comment by jrista** [comment]
A new factory function is being added to address the need to handle one or more actions across more than one entity type: `fromEntityActions`. This is akin to the existing `from` RxJs operator, in that it produces a stream of actions that match the specified criteria. 

```typescript
function fromEntityActions<TModel, T extends EntityAction<TModel>>(
  actions$: Actions,
  entity: Array<new () => TModel>,
  ...allowedActionTypes: EntityActionTypes[]
): Observable<Action>
```
